import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next js Routing Examples</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          <li>
          <Link href="/index-route">Index Route - folder about-index-route/index.js</Link>
          </li>
          <li>
          <Link href="/static-route" >Static Route - file static-route.js</Link>
          </li>
        </ul>

        <style jsx>{`
          li {
            padding: 25px;
            
          }     
  `}</style>



      </main>

    </div>
  )
}
